services:
  nextjs-dashboard-db:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: nextjs
      POSTGRES_PASSWORD: nextjs
      POSTGRES_DB: nextjs
